name: Release

on: [push, pull_request]

jobs:
  dist:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system

    steps:
    - uses: actions/checkout@v5

    - name: Install build dependencies
      run: python3 -m pip install --upgrade build twine

    - name: Build SDist and wheel
      run: python3 -m build --no-isolation --sdist

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*

    - name: Check metadata
      run: python3 -m twine check dist/*

  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    environment: pypi
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
